Update build-and-push-image.yml

diff --git a/.github/workflows/build-and-push-image.yml b/.github/workflows/build-and-push-image.yml
--- a/.github/workflows/build-and-push-image.yml
+++ b/.github/workflows/build-and-push-image.yml
@@ -2,7 +2,7 @@ name: Build Image and Publish to Dockerhub
 
 on:
   schedule:
-    - cron: '0 0 * * *'
+    - cron: '0 6 * * *'
   workflow_dispatch:
     inputs:
       tag:
@@ -26,7 +26,7 @@ jobs:
           ref: master
           fetch-depth: '0'
       
-      # 2. Get the latest release version and check for changes
+      # 2. Get the latest release version
       - name: Check for New Release
         id: check_release
         run: |
@@ -40,27 +40,40 @@ jobs:
 
           echo "LATEST_RELEASE=${latest_release}" >> $GITHUB_ENV
 
+      # 3. Download the previous release_version.txt as an artifact
+      - name: Download Release Version
+        id: download_version
+        uses: actions/download-artifact@v4
+        with:
+          name: release-version
+        continue-on-error: true # 允许下载失败，防止工作流中断
+
+      # 4. Compare the latest release with the previous version
+      - name: Compare Versions
+        id: compare_version
+        run: |
           if [ -f release_version.txt ]; then
             last_release=$(cat release_version.txt)
-            if [ "$last_release" = "${latest_release}" ]; then
+            echo "LAST_RELEASE=${last_release}" >> $GITHUB_ENV
+            if [ "$last_release" = "${{ env.LATEST_RELEASE }}" ]; then
               echo "No new release."
               echo "continue=false" >> $GITHUB_ENV
               exit 0
             fi
           fi
 
-          echo "${latest_release}" > release_version.txt
+          echo "${{ env.LATEST_RELEASE }}" > release_version.txt
           echo "continue=true" >> $GITHUB_ENV
 
-      # 3. Upload the release_version.txt as an artifact
+      # 5. Upload the release_version.txt as an artifact
       - name: Upload Release Version
         if: env.continue == 'true'
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v4
         with:
           name: release-version
           path: release_version.txt
 
-      # 4. Only run the following steps if there is a new release
+      # 6. Only run the following steps if there is a new release
       - name: Setup Docker Environment
         if: env.continue == 'true'
         run: |
@@ -76,7 +89,7 @@ jobs:
         if: env.continue == 'true'
         uses: docker/setup-buildx-action@v3
 
-      # 5. Login to DockerHub
+      # 7. Login to DockerHub
       - name: Login to DockerHub
         if: env.continue == 'true'
         uses: docker/login-action@v3
@@ -84,7 +97,7 @@ jobs:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_PASSWORD }}
 
-      # 6. Prepare Image Tags
+      # 8. Prepare Image Tags
       - name: Prepare Image Tags
         if: env.continue == 'true'
         run: |
@@ -92,16 +105,14 @@ jobs:
           echo "TAG_FRPC=${{ secrets.DOCKERHUB_USERNAME }}/frpc:${{ env.TAG_NAME }}" >> $GITHUB_ENV
           echo "TAG_FRPS=${{ secrets.DOCKERHUB_USERNAME }}/frps:${{ env.TAG_NAME }}" >> $GITHUB_ENV
 
-      # 7. 构建并推送镜像
-      - name: 构建并推送镜像
+      # 9. Build and push images
+      - name: Build and push images
         if: env.continue == 'true'
         run: |
           for service in frpc frps; do
-            echo "正在构建并推送 $service..."
-            DOCKERFILE_PATH="dockerfiles/Dockerfile-for-${service}"
-            if ! docker buildx build --platform linux/amd64,linux/arm64 --file $DOCKERFILE_PATH --tag ${{ secrets.DOCKERHUB_USERNAME }}/${service}:${{ env.TAG_NAME }} --push .; then
-              echo "构建并推送 $service 失败."
+            echo "Building and pushing $service..."
+            if ! docker buildx build --platform linux/amd64,linux/arm64 --file ./dockerfiles/Dockerfile-for-${service} --tag ${{ env.DOCKERFILE_${service^^}_PATH }} --push .; then
+              echo "Failed to build and push $service."
               exit 1
             fi
           done
-
